spring:
  # sentinel动态配置规则
  cloud:
    sentinel:
      datasource:
        # 限流
        ds1:
          nacos:
            server-addr: ${jfun.nacos-addr}
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            rule-type: flow
#        # 熔断
#        ds2:
#          nacos:
#            server-addr: ${jfun.nacos-addr}
#            dataId: sentinel-degrade
#            groupId: DEFAULT_GROUP
#            rule-type: degrade
#        # 系统负载保护
#        ds4:
#          nacos:
#            server-addr: ${jfun.nacos-addr}
#            dataId: sentinel-system
#            groupId: DEFAULT_GROUP
#            rule-type: system
      transport:
        dashboard: localhost:8080
jfun:
  nacos-addr: 127.0.0.1:8848