spring:
  application:
    name: gateway-jfun.service
# 路由跳转百度的例子
#  cloud:
#    gateway:
#      routes:
#      - id: rewritepath_route
#        uri: https://www.baidu.com
#        predicates:
#        - Path=/foo/**
#        filters:
#        - RewritePath=/foo/(?<segment>.*), /$\{segment}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/jfun_auth?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
server:
  port: 6003
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      db-type: mysql
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: jfun.entity
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: truejfun_auth.sql
  support-methods-arguments: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
  blog-url: www.xiejx.cn
  author: Miv
  version: 1.0
  description: jfun cloud