spring:
  application:
    name: gateway-server
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#  cloud:
#    gateway:
#      routes:
#        - id: header
#          uri: http://localhost:8888/header
#          filters:
#            - AddRequestHeader=header, addHeader
#            - AddRequestParameter=param, addParam
#          predicates:
#            - Path=/jd
server:
  port: 9005
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: debug
jfun:
  nacos-addr: 127.0.0.1:8848