spring:
  boot:  
    admin:  
      notify:  
        mail:  
          enabled: false
          to: 787824374@qq.com
          from: 787824374@qq.com
#          ignore-changes: UNKNOWN:UP  
          ignore-changes:  
            -  
              "*:UP" #从任何状态到up状态都不要发邮件通知  
      routes:  
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        #,unieap-eureka-server-single
        location: turbine  
  mail:
    host: smtp.qq.com
    username: 787824374@qq.com
    password: abmbwzivlvdkbdgi
    properties:
        mail.smtp.auth : true
        mail.smtp.timeout : 2000
        mail.smtp.starttls.enable : true
        mail.smtp.starttls.required : true 
server:
    port: 9007
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
