spring:
application:
  name: zuul-center
redis:
  host: 127.0.0.1
  port: 6379
security:
  oauth2:
    client:
      client-id: client_1
      client-secret: 123456
      access-token-uri: http://localhost:9004/oauth/token
      user-authorization-uri: http://localhost:9004/oauth/authorize
    resource:
      token-info-uri: http://localhost:9004/oauth/check_token
      id: order
server:
  port: 9005
zuul:
  routes:
    bd1:
      path: /bd1
      url: http://www.baidu.com/
    bd:
      url: http://www.baidu.com/
